name: gatsby-mysite CICD
on:
  push:
    branches: main
  repository_dispatch:
    types: [microCMS-Webhook]

jobs:
  gatsby-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Get .cache & public
        uses: actions/cache@v3
        id: gatsby_build_cache_id
        with:
          path: |
            .cache
            public
          key: ${{ runner.os }}-gatsby-build-cache

      - name: Get node_modules cache
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install
      
      - name: Build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          # githubのシークレットキーまたは.envで設定したメタデータを取得
          SITE_URL: ${{secrets.SITE_URL}}
          TWITTER_SITE: ${{secrets.TWITTER_SITE}}
          TWITTER_CREATOR: ${{secrets.TWITTER_CREATOR}}
          REPOSITORY_NAME: ${{secrets.REPOSITORY_NAME}}
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
        run: yarn build

      - name: add .nojekyll
        run: touch ./public/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
